### ISSUE TITLE
Классика. Квест "Реклама винного магазина" Штромград. Альянс

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/dragonwow#10]
При принятии квеста выдаётся "талон на вино". По прибытию на место сдачи, сам квест закончить невозможно. НПС не активен.
![image](https://github.com/admadm123/dragonwow/assets/148571583/26785f8f-1e17-4b87-a7ea-843cf4b3c82f)

**Comment by admadm123** [comment]
![image](https://github.com/admadm123/dragonwow/assets/63059326/ff1788c9-26ca-4601-ab44-006ee12c047f)
fix
