### ISSUE TITLE
Похоронный звон, начальная территория нежити. Квест "Вербовка"

### ISSUE THREAD

**Issue by Daemira** [admadm123/dragonwow#11]
![1](https://github.com/admadm123/dragonwow/assets/148588567/68759991-5731-4cd1-ba23-52ff115c043b)

Не собираются тела. При выходе из игры пропадает квестовый спутник Дарнелл, необходимо отменить и снова взять квест. При выборе тела открывается окно "Здравствуйте, (ник)" и ничего не происходит. Следующие квесты из-за этого недоступны.

**Comment by admadm123** [comment]
fix
