### ISSUE TITLE
Облик друида

### ISSUE THREAD

**Issue by Bear891** [admadm123/dragonwow#25]
Не работает квест. https://www.wowhead.com/ru/quest=59951/%D0%BE%D0%B1%D0%BB%D0%B8%D0%BA-%D0%B4%D1%80%D1%83%D0%B8%D0%B4%D0%B0
![WoWScrnShot_102123_105829](https://github.com/admadm123/dragonwow/assets/148621606/234313a0-c739-4406-a005-d2fe58d003d8)

**Comment by admadm123** [comment]
это необязательный квест старый, не удаленный мной. он не нужен облик дается автоматически по достижению нного уровня
