### ISSUE TITLE
Сбор иллидари: Пеплоусты

### ISSUE THREAD

**Issue by Bear891** [admadm123/dragonwow#26]
Не завершается квест при разговоре. https://www.wowhead.com/ru/quest=40378/%D1%81%D0%B1%D0%BE%D1%80-%D0%B8%D0%BB%D0%BB%D0%B8%D0%B4%D0%B0%D1%80%D0%B8-%D0%BF%D0%B5%D0%BF%D0%BB%D0%BE%D1%83%D1%81%D1%82%D1%8B
![WoWScrnShot_102123_101540](https://github.com/admadm123/dragonwow/assets/148621606/847071ef-19ab-4690-847c-b3de18e46261)

**Comment by admadm123** [comment]
исправлено

**Comment by admadm123** [comment]
![image](https://github.com/admadm123/dragonwow/assets/63059326/51124a5b-d990-4292-bb5d-8b6e3394f996)
