### ISSUE TITLE
Камень возвращения

### ISSUE THREAD

**Issue by Bear891** [admadm123/dragonwow#29]
Отсутствует камень возвращения у персонажа. https://www.wowhead.com/ru/item=6948/%D0%BA%D0%B0%D0%BC%D0%B5%D0%BD%D1%8C-%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D1%8F
![WoWScrnShot_102123_131438](https://github.com/admadm123/dragonwow/assets/148621606/f07217d7-0c48-4b84-a60d-b0dfc9926c4d)

**Comment by admadm123** [comment]
какая расса и когда персонаж был создан?

**Comment by admadm123** [comment]
fix
