### ISSUE TITLE
Dragonflight. Охотник на Демонов. Навык "Рывок Скверны".

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/dragonwow#49]
По описанию навыка должен наноситься урон, урона нету.
![image](https://github.com/admadm123/dragonwow/assets/148571583/7774f979-944f-42c0-8e1b-6ee591556158)

**Comment by admadm123** [comment]
способность вообще не работала, сделал такой временный фикс, урон будет позже, я не забыл
