### ISSUE TITLE
Dragonflight. Dragonflight. Полёты после смерти.

### ISSUE THREAD

**Issue by m1LOMAN** [admadm123/dragonwow#50]
После смерти от дебафа который был бесконечен. Подлетел к трупу на драконе и возродился. Персонаж стал летать как будто на маунте. Ну или как у тебя с ГМом. https://disk.yandex.ru/i/iOBM5bFzBzNKxw

**Comment by m1LOMAN** [comment]
UPD: Если сесть на маунта (маунт летает без навыка на дракноньиъ островах) и выйти с него то ничего не происходит. Всё остаётся таким же.

**Comment by admadm123** [comment]
призрачные полеты выключены до выяснения причины почему не снимается аури при ресе персонажа
