### ISSUE TITLE
Dragonflight. баг после релога

### ISSUE THREAD

**Issue by Altaxa-Tyrbowow** [admadm123/dragonwow#57]
![image](https://github.com/admadm123/dragonwow/assets/148558494/7027f606-0a40-4c78-9b5c-403f36482258)
После релога находясь на дракоше, при входе можно с медленной скоростью летать без маунта.

**Comment by admadm123** [comment]
problem solved. There was a custom hotfix in the database with an aura. closed

**Comment by admadm123** [comment]
данной проблемы не обнаружено
